### PR TITLE
AI will choose player by random if there are players with the same amount of influences and money

### PR DESCRIPTION
**Pull request by einsteinsfool**
Sometimes I can make a decision based on knowing that AI will assasinate or coup the first player from the list if there is more than 1 player with most incluences and cash.
I think I shouldn't be able to do that and that AIs should be less predictable.
For more explanation check out comments in sort function.

After pulling this, a `npm install` is needed as I added a new module "md5" for calculating hash functions.

### CODE REVIEW

**Comment by octachrome** [comment]
Have you run the unit tests to make sure they still pass?

    npm test

**Comment by einsteinsfool** [comment]
No, I didn't run the tests. I'll comment after I run them.

I think you can't just return -1 or 1 by random, because the function must be deterministic and return the same value every time for every input. And random numbers are based on time which changes.
Read the last bullet point [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#Description).

**Comment by einsteinsfool** [comment]
All tests pass. I'll run them before every PR from now, thanks.

**Comment by octachrome** [comment]
You could generate a random number before calling sort, and append it to each player name before hashing (instead of the node modules). That way the tie will be broken differently every time the function is called.

**Comment by einsteinsfool** [comment]
Right. :D Good, idea.
Fixed and tested both with npm and myself (once I was stolen from and once AI was stolen from).

**Comment by octachrome** [comment]
Thanks again for another pr!

**Pull request merged**
